"""Analysis History migration

Revision ID: 0fda92708854
Revises: 19a86f6bbfe8
Create Date: 2026-03-21 23:53:50.792235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0fda92708854'
down_revision: Union[str, Sequence[str], None] = '19a86f6bbfe8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('session_token', sa.String(length=255), nullable=True))
    op.create_unique_constraint(None, 'users', ['session_token'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'session_token')
    # ### end Alembic commands ###
